INPUT:
  RIBOSOMAL_PROTEINS_COUNT_THRESHOLD: 10
  EXPRESSION_PERCENTAGE_THRESHOLD: 0.15
INITIATION:
  NUMBER_OF_CODONS_TO_OPTIMIZE: 12
  MAX_ITERATIONS: 50
ORF:
  ZSCORE_MAX_ITERATIONS: 50
  ZSCORE_INITIAL_PERMUTATIONS_NUM: 3
  MAX_N_OPTIMIZED_SEQS: 10
