INPUT:
  RIBOSOMAL_PROTEINS_COUNT_THRESHOLD: 10
  EXPRESSION_PERCENTAGE_THRESHOLD: 0.15
INITIATION:
  NUMBER_OF_CODONS_TO_OPTIMIZE: 15
  MAX_ITERATIONS: 50
  EXTERNAL_INITIATION_ORF: "ATGGTTTCAAAAGGGGAGGAGGACAATATGGCAATTATCAAAGAATTCATGCGCTTCAAAGTTCACATGGAGGGTTCTGTTAACGGTCACGAGTTCGAGATCGAAGGCGAAGGCGAGGGCCGTCCGTATGAAGGCACCCAGACCGCCAAACTGAAAGTGACTAAAGGCGGCCCGCTGCCTTTTGCGTGGGACATCCTGAGCCCGCAATTTATGTACGGTTCTAAAGCGTATGTTAAACACCCAGCGGATATCCCGGACTATCTGAAGCTGTCTTTTCCGGAAGGTTTCAAGTGGGAACGCGTAATGAATTTTGAAGATGGTGGTGTCGTGACCGTCACTCAGGACTCCTCCCTGCAGGATGGCGAGTTCATCTATAAAGTTAAACTGCGTGGTACTAATTTTCCATCTGATGGCCCGGTGATGCAGAAAAAGACGATGGGTTGGGAGGCGTCTAGCGAACGCATGTATCCGGAAGATGGTGCGCTGAAAGGCGAAATTAAACAGCGCCTGAAACTGAAAGATGGCGGCCATTATGACGCTGAAGTGAAAACCACGTACAAAGCCAAGAAACCTGTGCAGCTGCCTGGCGCGTACAATGTGAATATTAAACTGGACATCACCTCTCATAATGAAGATTATACGATCGTAGAGCAATATGAGCGCGCGGAGGGTCGTCATTCTACCGGTGGCATGGATGAGCTGTACAAATAA"
ORF:
  ZSCORE_MAX_ITERATIONS: 50
  ZSCORE_INITIAL_PERMUTATIONS_NUM: 3
  FREQUENCY_OPTIMIZATION_THRESHOLD: 0.1
  DEDUP_CODONS: False
